### ISSUE TITLE
Tristan and Isolde 

### ISSUE THREAD

**Issue by CottageInTheCity** [vck3000/ProAvalon#124]
Not sure if this belongs in here or in suggestions, since they may both be intentional, however I feel that they are both (minor) issues.

Firstly, you can create games with Isolde and without Tristan, and vice versa. Not sure if this is intended but it feels wrong as they are supposed to function as lovers.

Secondly, you can create games with Isolde and Tristan without Assassin. I was under the impression that if there is no Merlin present, then Assassin must try to guess both Isolde and Tristan. What's the motivation for Isolde and Tristan to not reveal if there is no Assassin?

**Comment by vck3000** [comment]
At the moment, the site requires players be decently smart with selection of roles. Of course both points you mentioned are valid, and indeed should probably have restrictions on them to not allow games that are obviously imbalanced, but I have not thought about implementing that kind of restriction in so far. 

It won't be too hard to code in, but I don't think it is as big a problem when compared to for example if assassin could pick all the res players and then shoot (because the server would only accept one shot, but which shot? (answer is the lowest player number 0 at the top, increasing anti clockwise)). 

If I had the budget and time of a massive game company then ofc it could easily be solved! haha
