### ISSUE TITLE
Highlight picks when hovering over PickBoxes for current mission

### ISSUE THREAD

**Issue by NiharS** [vck3000/ProAvalon#162]
Hello! I am looking into implementing this feature, just wanted to check if this is an acceptable feature first.

**Is your feature request related to a problem? Please describe.**
This is a QoL improvement, not related to a bug.

**Describe the solution you'd like**
Right now, when hovering over a completed mission, the avatars of people who went on the mission are highlighted. I'd like to add the same functionality to the "5 dots" below the missions, that track the pick number we're on for that mission. In this case, hovering over a filled dot would highlight who was on that pick (i.e. if someone is currently picking 3.4, people can hover over the first dot to see who was picked on the rejected 3.1 team).

**Describe alternatives you've considered**
I was thinking if it'd be possible to extend this to previous missions as well, but I feel the UI might get too cluttered at that point. Please let me know if you think there's a good design for this!

**Comment by vck3000** [comment]
That looks like a good one to work on! One improvement to the current highlighting system I'd like to suggest is to somehow distinguish who the leader of that team was. Maybe the team leader can have a red highlight instead of a yellow one. Up to you how to implement this if you want to try it :). But otherwise, the teams on each pick for the dot is a good one to try.

Just one thing, players would only be able to see the teams for the current mission picked. E.g. if it was m3.4 right now, they cant see 1.3. They'd still have to check VH.

**Comment by bocaben** [comment]
this was implemented and merged, no? if so, this issue can be closed

**Comment by NiharS** [comment]
Yup, closing this
