### ISSUE TITLE
Fix stats percentages. 

### ISSUE THREAD

**Issue by vck3000** [vck3000/ProAvalon#198]
Some tables have inconsistent (i.e. don't add up to 100%) statistics...

**Comment by piguyinthesky** [comment]
I figured out what the problem is: several of the entries in the records have no "howTheGameWasWon" attribute. I ran this code in a shell with the data downloaded from the site:
```
const records = require("./assets/gameRecordsData/gameRecordsDataAnon.json")
for (let i = 0; i < records.length; i++)
    if (records[i].winningTeam === "Spy")
        console.log(records[i].howTheGameWasWon)
```
I put the results in [a gist here](https://gist.github.com/piguyinthesky/65f18d9cb5d50fcc5ac25c4c52d7f6f3).
I think we should just create an "other" category so that it lines up? The rest of the tables look ok to me.

**Comment by vck3000** [comment]
At the moment, I haven't allowed outside access to the database, so you can't directly query the database. The only way for me to export the data to share with others was to export it into a large JSON file. Do you have any suggestions for this? Would the best way to approach this be to host a second (but public) mongoDB database?

**Comment by vck3000** [comment]
Also good catch. I had previously run a complete fix for another field (I believe it was "gameMode), but I don't think that would have affected it. I will check it up.

**Comment by piguyinthesky** [comment]
If you want to migrate to an online database, it would be as simple as creating one online, such as via [MongoDB Atlas](https://www.mongodb.com/cloud/atlas), and changing the URL in the code. You could possibly create a [readonly user](https://docs.atlas.mongodb.com/security-add-mongodb-users/#Only-read-any-database) that we could use for testing, and have a single admin user that the Heroku server can use to read and write to the database.
